CREATE TABLE [dbo].[JobPackageSchedule] (
    [JobId]                     INT           NOT NULL,
    [PackageId_Channel1]        INT           NOT NULL,
    [IntParameter_Channel1]     INT           NULL,
    [VarcharParameter_Channel1] VARCHAR (128) NULL,
    [PackageId_Channel2]        INT           NULL,
    [IntParameter_Channel2]     INT           NULL,
    [VarcharParameter_Channel2] VARCHAR (128) NULL,
    [PackageId_Channel3]        INT           NULL,
    [IntParameter_Channel3]     INT           NULL,
    [VarcharParameter_Channel3] VARCHAR (128) NULL,
    [PackageId_Channel4]        INT           NULL,
    [IntParameter_Channel4]     INT           NULL,
    [VarcharParameter_Channel4] VARCHAR (128) NULL,
    [PackageId_Channel5]        INT           NULL,
    [IntParameter_Channel5]     INT           NULL,
    [VarcharParameter_Channel5] VARCHAR (128) NULL,
    [PackageId_Channel6]        INT           NULL,
    [IntParameter_Channel6]     INT           NULL,
    [VarcharParameter_Channel6] VARCHAR (128) NULL,
    [PackageId_Channel7]        INT           NULL,
    [IntParameter_Channel7]     INT           NULL,
    [VarcharParameter_Channel7] VARCHAR (128) NULL,
    [PackageId_Channel8]        INT           NULL,
    [IntParameter_Channel8]     INT           NULL,
    [VarcharParameter_Channel8] VARCHAR (128) NULL,
    [ExecutionOrder]            INT           NOT NULL,
    CONSTRAINT [PkPackageRunOrder] PRIMARY KEY CLUSTERED ([JobId] ASC, [PackageId_Channel1] ASC, [ExecutionOrder] ASC),
    CONSTRAINT [FkProJobId] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Job] ([Id]),
    CONSTRAINT [FkProPackageId_Channel1] FOREIGN KEY ([PackageId_Channel1]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel2] FOREIGN KEY ([PackageId_Channel2]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel3] FOREIGN KEY ([PackageId_Channel3]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel4] FOREIGN KEY ([PackageId_Channel4]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel5] FOREIGN KEY ([PackageId_Channel5]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel6] FOREIGN KEY ([PackageId_Channel6]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel7] FOREIGN KEY ([PackageId_Channel7]) REFERENCES [dbo].[Package] ([Id]),
    CONSTRAINT [FkProPackageId_Channel8] FOREIGN KEY ([PackageId_Channel8]) REFERENCES [dbo].[Package] ([Id])
);

